#!/usr/bin/env bash
#This script displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

b=0
while [ $b -lt 10 ]
do
	echo "Best School"
	if [ $b -eq 8 ]
		echo "Best School"
		echo "Hi"
	fi
	((b++))
done
