#!/usr/bin/env bash
#this script loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

b=1
while [ $b -le 10 ]
do
	if [ $b -eq 4 ]
	then
		echo "bad luck"
	elif [ $b -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((b++))	
done
